typography_spectrum: 0.5602353673427376
content_rating:
  adult: false
color:
  brandColors:
    - '#908E68'
    - '#FBBC2F'
    - '#606346'
    - '#17170F'
    - '#F4EDD0'
  brandStrength: 0.4707537173448444
  lightness: 0.4089275928509265
  saturation: 0.2135508711024713
  rhythmicContrast: 0.10364345739512604
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.19290696744548877
author:
  name: 'Johanna '
  url: ''
  email: j.pilwarsch@gmail.com
name: 'even Venus needs a midwife '
navigation:
  - name: sommer
    id: 83ba7a25-25d4-4ce6-98ac-cf7c3fa2fc5b
    type: content
  - name: toskany
    id: 3972600e-c4a1-4c3c-a18a-906e520d3e08
    type: content
  - name: herbs
    id: 50d8456e-b644-4b66-8d24-5219a2e2e223
    type: content
  - name: sun
    id: 1c42c904-4a7b-498e-8d44-4a3e3fc6a7f9
    type: content
  - name: autumn
    id: 0d5a3a80-462c-4255-b52d-bc1b3f1d1974
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6a567039-4c6e-4222-9e61-021c391cb1d7.ico
title: augenblickdetektivin
content: []
description: ''
purpose:
  - type: contact
    url: 'mailto:j.pilwarsch@gmail.com'
    label: briefe
  - type: external
    url: 'https://www.instagram.com/johannerli/'
    label: instagram
