layout_spectrum: 0.5359629011101615
typography_spectrum: 0.7143710796254696
color:
  brandColors:
    - '#908E68'
    - '#FBBC2F'
    - '#606346'
    - '#17170F'
    - '#F4EDD0'
  brandStrength: 0.8602492685378114
  lightness: 0.9164620828223737
  saturation: 0.7557499304409185
  rhythmicContrast: 0.8584177208372789
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
author:
  name: 'Johanna '
  url: ''
  email: j.pilwarsch@gmail.com
name: 'even Venus needs a midwife '
navigation:
  - name: sommer
    id: 83ba7a25-25d4-4ce6-98ac-cf7c3fa2fc5b
    type: content
  - name: toskany
    id: 3972600e-c4a1-4c3c-a18a-906e520d3e08
    type: content
  - name: herbs
    id: 50d8456e-b644-4b66-8d24-5219a2e2e223
    type: content
  - name: sun
    id: 1c42c904-4a7b-498e-8d44-4a3e3fc6a7f9
    type: content
  - name: autumn
    id: 0d5a3a80-462c-4255-b52d-bc1b3f1d1974
    type: content
title: augenblickdetektivin
content: []
description: ''
purpose:
  - type: contact
    url: 'mailto:j.pilwarsch@gmail.com'
    label: briefe
  - type: external
    url: 'https://www.instagram.com/johannerli/'
    label: instagram
