typography_spectrum: 0.9820112376521793
content_rating:
  adult: false
color:
  brandColors:
    - '#939067'
    - '#FFB31C'
    - '#5E6342'
    - '#110F06'
    - '#B2D7FF'
  brandStrength: 0.5972442649743787
  lightness: 0.9804773061113929
  saturation: 0.313279466767528
  rhythmicContrast: 0.02774397364227415
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.3164221715028997
author:
  name: 'Johanna '
  url: ''
  email: j.pilwarsch@gmail.com
name: 'even Venus needs a midwife '
navigation:
  - name: Kontakt
    id: d6135363-8b5f-4591-9837-20ba96f5db3c
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6a567039-4c6e-4222-9e61-021c391cb1d7.ico
title: Johanna Pilwarsch
content: []
description: ''
purpose:
  - type: internal
    label: comment
    item: d6135363-8b5f-4591-9837-20ba96f5db3c
  - type: external
    url: 'https://www.instagram.com/johannerli/'
    label: instagram
